spring.application.name=clean-arch
spring.datasource.url=jdbc:postgresql://localhost:5432/cleanArchDb
spring.datasource.username=postgres
spring.datasource.password=postgres@123
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true